language: node_js
services: mongodb
install:
  - npm install
before_script:
  - npm install -g gulp
  - npm install -g mocha
  - npm install -g phantomjs
  - npm install -g casperjs
script: gulp test
